apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap-readfile
data:
  {{- $files := .Files }}
  {{- range tuple "config1.toml" "config2.toml" "config3.toml" }}
  {{ . }}: |-
    {{ $files.Get . }}    
  {{- end }}
  {{- range $path, $_ :=  .Files.Glob  "**.toml" }}
    {{ $.Files.Get $path }}
  {{- end }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: conf
data:
{{ (.Files.Glob "foo/*").AsConfig | indent 2 }}
  some-file.txt: {{ range .Files.Lines "foo/foo.txt" }}
    {{ . }}{{ end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: very-secret
type: Opaque
data:
{{ (.Files.Glob "bar/*").AsSecrets | indent 2 }}
  token: |-
    {{ .Files.Get "config1.toml" | b64enc }}